#!/bin/bash

LOCALDIR=`cd "$( dirname ${BASH_SOURCE[0]} )" && pwd`
cd $LOCALDIR

rm -rf $1/data-app/*
rm -rf $1/data-app/MiCreditInStub
rm -rf $1/data-app/XMRemoteController
rm -rf $1/app/AnalyticsCore
rm -rf $1/app/BTProductionLineTool
rm -rf $1/app/BasicDreams
rm -rf $1/app/BookmarkProvider
rm -rf $1/app/CatchLog
rm -rf $1/app/CertInstaller
rm -rf $1/app/Cit
rm -rf $1/app/CloudService 
rm -rf $1/dapp/CompanionDeviceManager
rm -rf $1/app/EasterEgg
rm -rf $1/app/FidoAuthen
rm -rf $1/dapp/FidoClient
rm -rf $1/app/HTMLViewer
rm -rf $1/app/HybridAccessory
rm -rf $1/app/HybridPlatform
rm -rf $1/app/InMipay
rm -rf $1/app/Joyose
rm -rf $1/app/KeyChain
rm -rf $1/app/MIDrop
rm -rf $1/app/MIRadioGlobalBuiltin
rm -rf $1/app/MIUICalculatorGlobal
rm -rf $1/app/MIUICompassGlobal
rm -rf $1/app/MIUIFrequentPhrase
rm -rf $1/app/MIUIGuardProviderGlobal 
rm -rf $1/app/MIUIHealthGlobal
rm -rf $1/app/MIUIMiPicks
rm -rf $1/app/MIUINotes
rm -rf $1/app/MIUIVideoPlayer
rm -rf $1/app/MIWallpaper
rm -rf $1/app/MSA-Global
rm -rf $1/app/MSA-Global
rm -rf $1/app/MiCloudSync
rm -rf $1/app/MiConnectService
rm -rf $1/app/MiLinkGlobal
rm -rf $1/app/MiPlayClient
rm -rf $1/app/MiuiBugReport
rm -rf $1/app/MiuiDaemon
rm -rf $1/app/MiuiSecurityAddGlobal
rm -rf $1/app/MiuixEditor_global
rm -rf $1/app/PartnerBookmarksProvider
rm -rf $1/app/PaymentService
rm -rf $1/app/Protips
rm -rf $1/app/SecureElement
rm -rf $1/app/WMService
rm -rf $1/app/XMSFKeeperAll
rm -rf $1/app/facebook-appmanager
rm -rf $1/priv-app/CleanMaster
rm -rf $1/priv-app/CloudBackup
rm -rf $1/priv-app/CloudServiceSysbase
rm -rf $1/priv-app/MIShareGlobal
rm -rf $1/priv-app/MIService
rm -rf $1/priv-app/MusicFX
rm -rf $1/priv-app/facebook-installer
rm -rf $1/priv-app/facebook-services
